### ISSUE TITLE
Correct Agile hyperlink to redirect to Agile Alliance

### ISSUE THREAD

**Issue by linuxwebexpert** [vta/devops#3]
|#350 - https://projects.vta.org/projects/devops-server/work_packages/350/activity

Reviewing the hyperlinks and references identified an old outdated link.

- [x] Update Agile hyperlink to the reference given in the Wiki pages
- [x] https://www.agilealliance.org/agile-essentials/

**Comment by bijanmmarkes** [comment]
Fixes #3
